Added a healing booster and a control reroll check to WASD
bmstu-iu9/ptp2021-5-2d-game pull request #14
Opened 2021-07-08 12:40 UTC by artem-yadr

2021-07-08 13:01 UTC, alien-agent requested changes
Класс Boosters лучше переименовать в BaseBooster по аналогии с остальными классами проекта. Применять позитивный эффект бустера **нужно в CollisionRule**, т.к. метод destroy() вызывается не только при столкновении бустера с игроком, но и например при выходе за границы игрового поля

2021-07-08 13:03 UTC, Mazdaywik commented on js/player/keyboard_control.js
> +function configureKeyWatchers(wasd) {
А где вызывается эта функция?

2021-07-08 13:07 UTC, alien-agent commented on js/player/keyboard_control.js
> +function configureKeyWatchers(wasd) {
game.js -> Game.load()
Передача параметра wasd из настроек будет реализована мной

2021-07-08 13:09 UTC, Mazdaywik commented on js/player/keyboard_control.js
> +function configureKeyWatchers(wasd) {
Тогда, раз код ещё не дописан, запрос на слияние стоит сделать черновиком.

2021-07-08 13:10 UTC, Mazdaywik commented on js/player/keyboard_control.js
> +function configureKeyWatchers(wasd) {
Сделал черновиком. Когда получится чистовой вариант, достойный слияния, нажмите снизу кнопку
![image](https://user-images.githubusercontent.com/1309859/124927214-0ea4b400-e007-11eb-9b23-9aadf8d6e2cc.png)

2021-07-08 15:57 UTC, Mazdaywik commented
Про WASD. Лучше делать не опцию настройки: либо WASD, либо ↑←↓→, а поддерживать оба набора кнопок одновременно.

2021-07-08 18:27 UTC, alien-agent approved these changes

2021-07-08 18:29 UTC, alien-agent approved these changes
Cool

2021-07-08 18:29 UTC, merged

2021-07-17 12:19 UTC, Mazdaywik reviewed
Пример комментария к строчке.

2021-07-17 12:19 UTC, Mazdaywik commented on index.html
> +            <div class="page-item button" id="menu-settings" onclick="switchPage('settings')"><p>SETTINGS</p></div>
Комментарий к строчке